---
- src: https://github.com/ansible-community/ansible-consul.git
  name: ansible-consul
  scm: git
  version: master

- src: https://github.com/ansible-community/ansible-nomad
  name: ansible-nomad
  scm: git
  version: master

- src: https://github.com/ansible-community/ansible-vault.git
  name: ansible-community.ansible-vault
  scm: git
  version: master