defaultEntryPoints = ["http", "https"]
# debug = true
# logLevel = "DEBUG"
accesslog = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true

[providers]
  [providers.file]
    filename = "/etc/traefik/config/dynamic.toml"
    watch = true
  [providers.docker]

[certificatesresolvers.letsencrypt.acme]
  email = "forestkzanderson@gmail.com"
  storage = "/letsencrypt/acme.json"
  [certificatesresolvers.letsencrypt.acme.httpchallenge]
    entrypoint = "http"
