---
- hosts: all
  remote_user: student
  become: true
  
  tasks:
    - name: Change user password
      user:
        name: student
        update_password: always
        password: "{{ 'newpassword'|password_hash('sha512') }}"