---
k3s_instances:
  hosts:
    rancher-1:
      ansible_host: 192.168.50.11
    rancher-2:
      ansible_host: 192.168.50.136
    rancher-3:
      ansible_host: 192.168.50.205
bastion:
  hosts:
    bastion-1:
      ansible_host: 134.117.26.239
k3s_server:
  hosts:
    rancher-1:
      ansible_host: 192.168.50.11
k3s_agent:
  hosts:
    rancher-2:
      ansible_host: 192.168.50.136
    rancher-3:
      ansible_host: 192.168.50.205